// RD-9 - device logic.
// PIDs: 0x1242, 0x1243 | protocol(s): 3
// Functions: General, Sequencer, Update
// @generated by scripts/gen_device_dirs.mjs; add a "// @keep" line to hand-edit.
import def from '../../data/devices/rd-9.json';
import { genericDriver, type DriverFactory } from '../_shared/driver';
import type { DeviceDef } from '../../lib/types';

export const definition = def as unknown as DeviceDef;

// swap for a DeviceDriver subclass to override behaviour
export const driver: DriverFactory = genericDriver;

export const hasSequencer = true;

export default { definition, driver, hasSequencer };
