// GRIND - device logic.
// PIDs: 0x12a7, 0x12a8 | protocol(s): 1
// Functions: General, Sequencer, PolyChain, Update
// @generated by scripts/gen_device_dirs.mjs; add a "// @keep" line to hand-edit.
import def from '../../data/devices/grind.json';
import { genericDriver, type DriverFactory } from '../_shared/driver';
import type { DeviceDef } from '../../lib/types';

export const definition = def as unknown as DeviceDef;

// swap for a DeviceDriver subclass to override behaviour
export const driver: DriverFactory = genericDriver;

export const hasSequencer = true;

export default { definition, driver, hasSequencer };
