// UB-Xa 16 - device logic.
// PIDs: 0x125b, 0x125c | protocol(s): 3
// Functions: General, #Atrophy, #Preset, Librarian, Update
// @generated by scripts/gen_device_dirs.mjs; add a "// @keep" line to hand-edit.
import def from '../../data/devices/ub-xa-16.json';
import { genericDriver, type DriverFactory } from '../_shared/driver';
import type { DeviceDef } from '../../lib/types';

export const definition = def as unknown as DeviceDef;

// swap for a DeviceDriver subclass to override behaviour
export const driver: DriverFactory = genericDriver;

export const hasSequencer = false;

export default { definition, driver, hasSequencer };
