// PRO-1 - device logic.
// PIDs: 0x1220, 0x1221 | protocol(s): 1
// Functions: General, PolyChain, Update
// @generated by scripts/gen_device_dirs.mjs; add a "// @keep" line to hand-edit.
import def from '../../data/devices/pro-1.json';
import { genericDriver, type DriverFactory } from '../_shared/driver';
import type { DeviceDef } from '../../lib/types';

export const definition = def as unknown as DeviceDef;

// swap for a DeviceDriver subclass to override behaviour
export const driver: DriverFactory = genericDriver;

export const hasSequencer = false;

export default { definition, driver, hasSequencer };
