// Device artwork resolver: slug (+ optional variant) -> optimized image under
// /devices/, generated by scripts/extract_images.py.
import images from '../data/device-images.json';

interface ImgEntry {
  image: string;
  variants: Record<string, string>;
}

const MAP = images as Record<string, ImgEntry>;

// primary image for a device slug, or undefined
export function deviceImage(
  slug: string,
  variant?: string,
): string | undefined {
  const e = MAP[slug];
  if (!e) return undefined;
  if (variant && e.variants[variant]) return e.variants[variant];
  return e.image;
}

// full-resolution artwork for the zoom modal (pipeline emits thumb+full pairs)
export function deviceImageFull(
  slug: string,
  variant?: string,
): string | undefined {
  const thumb = deviceImage(slug, variant);
  return thumb ? thumb.replace('/devices/', '/devices/full/') : undefined;
}
