// JT-4000 MICRO - device logic.
// PIDs: 0x127d, 0x127e, 0x12c7, 0x12c8 | protocol(s): 2
// Functions: General, Update
// @generated by scripts/gen_device_dirs.mjs; add a "// @keep" line to hand-edit.
import def from '../../data/devices/jt-4000-micro.json';
import { genericDriver, type DriverFactory } from '../_shared/driver';
import type { DeviceDef } from '../../lib/types';

export const definition = def as unknown as DeviceDef;

// swap for a DeviceDriver subclass to override behaviour
export const driver: DriverFactory = genericDriver;

export const hasSequencer = false;

export default { definition, driver, hasSequencer };
