// MODEL D - device logic.
// PIDs: 0x1214, 0x1215 | protocol(s): 0
// Functions: General, PolyChain, Calibration, Update
// @generated by scripts/gen_device_dirs.mjs; add a "// @keep" line to hand-edit.
import def from '../../data/devices/model-d.json';
import { genericDriver, type DriverFactory } from '../_shared/driver';
import type { DeviceDef } from '../../lib/types';

export const definition = def as unknown as DeviceDef;

// swap for a DeviceDriver subclass to override behaviour
export const driver: DriverFactory = genericDriver;

export const hasSequencer = false;

export default { definition, driver, hasSequencer };
